services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: importador_de_produto_app
    volumes:
      - ./app:/var/www
      - ./csv:/var/www/csv
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: importador_de_produto
      DB_USERNAME: importador_de_produto
      DB_PASSWORD: importador_de_produto
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8.0
    container_name: importador_de_produto_db
    environment:
      MYSQL_DATABASE: importador_de_produto
      MYSQL_USER: importador_de_produto
      MYSQL_PASSWORD: importador_de_produto
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
